/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarPersona extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarPersona() {
        initComponents();
        this.setSize(543,520);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDP1 = new javax.swing.JButton();
        boton_Volver_RegistroDP1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Pais = new javax.swing.JLabel();
        label_nombre_Per = new javax.swing.JLabel();
        field_Nombre_Persona = new java.awt.TextField();
        label_Apellido_Per = new javax.swing.JLabel();
        field_Numero_Doc = new java.awt.TextField();
        label_Numero_Doc = new javax.swing.JLabel();
        field_Apellido_Persona = new java.awt.TextField();
        label_Fecha_Nac = new javax.swing.JLabel();
        label_Municipio = new javax.swing.JLabel();
        label_Sexo = new javax.swing.JLabel();
        label_Estado = new javax.swing.JLabel();
        desplegable_Estado = new javax.swing.JComboBox<>();
        desplegable_Nacionalidad = new javax.swing.JComboBox<>();
        desplegable_Pais = new javax.swing.JComboBox<>();
        desplegable_Municipio1 = new javax.swing.JComboBox<>();
        desplegable_Sexo1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        title_persona = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDP1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDP1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDP1.setText("Siguiente");
        boton_Siguiente_RegistroDP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDP1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 80, 27));

        boton_Volver_RegistroDP1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP1.setText("Volver");
        boton_Volver_RegistroDP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 154, 110));

        label_Pais.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Pais.setText("País: ");
        jPanel2.add(label_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label_nombre_Per.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_nombre_Per.setText("Nombre:");
        jPanel2.add(label_nombre_Per, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        field_Nombre_Persona.setBackground(new java.awt.Color(235, 235, 235));
        field_Nombre_Persona.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_Nombre_Persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 180, -1));

        label_Apellido_Per.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Apellido_Per.setText("Apellido:");
        jPanel2.add(label_Apellido_Per, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        field_Numero_Doc.setBackground(new java.awt.Color(235, 235, 235));
        field_Numero_Doc.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_Numero_Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 180, -1));

        label_Numero_Doc.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Numero_Doc.setText("Número de documento:");
        jPanel2.add(label_Numero_Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        field_Apellido_Persona.setBackground(new java.awt.Color(235, 235, 235));
        field_Apellido_Persona.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_Apellido_Persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 180, -1));

        label_Fecha_Nac.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac.setText("Fecha de Nacimiento: ");
        jPanel2.add(label_Fecha_Nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label_Municipio.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Municipio.setText("Municipio:");
        jPanel2.add(label_Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        label_Sexo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Sexo.setText("Sexo: ");
        jPanel2.add(label_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        label_Estado.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Estado.setText("Estado: ");
        jPanel2.add(label_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        desplegable_Estado.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Estado.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 180, -1));

        desplegable_Nacionalidad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        desplegable_Nacionalidad.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 40, -1));

        desplegable_Pais.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Pais.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_PaisActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 180, -1));

        desplegable_Municipio1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Municipio1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Municipio1.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Municipio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 180, -1));

        desplegable_Sexo1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Sexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M", "N/A" }));
        desplegable_Sexo1.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Sexo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, -1));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 370));

        title_persona.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona.setText("Registro de datos personales");
        jPanel1.add(title_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroDP1ActionPerformed

    private void boton_Siguiente_RegistroDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_RegistroDP1ActionPerformed

    private void desplegable_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_PaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Siguiente_RegistroDP1;
    private javax.swing.JButton boton_Volver_RegistroDP1;
    private javax.swing.JComboBox<String> desplegable_Estado;
    private javax.swing.JComboBox<String> desplegable_Municipio1;
    private javax.swing.JComboBox<String> desplegable_Nacionalidad;
    private javax.swing.JComboBox<String> desplegable_Pais;
    private javax.swing.JComboBox<String> desplegable_Sexo1;
    private java.awt.TextField field_Apellido_Persona;
    private java.awt.TextField field_Nombre_Persona;
    private java.awt.TextField field_Numero_Doc;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Apellido_Per;
    private javax.swing.JLabel label_Estado;
    private javax.swing.JLabel label_Fecha_Nac;
    private javax.swing.JLabel label_Municipio;
    private javax.swing.JLabel label_Numero_Doc;
    private javax.swing.JLabel label_Pais;
    private javax.swing.JLabel label_Sexo;
    private javax.swing.JLabel label_nombre_Per;
    private javax.swing.JLabel title_persona;
    // End of variables declaration//GEN-END:variables
}
