/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import tools.Buscador;
import tools.Creador;
import tools.Verificador;
import SQL.Guardar;
import SQL.Extraer;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/**
 *
 * @author Ricardo Fanghella
 */
public class RegistroVisualizacionPersonasContagiadas extends javax.swing.JFrame {
    Buscador bus = new Buscador();
    Creador crea = new Creador();
    Extraer dataSQL = new Extraer();
    DefaultTableModel model;
    DefaultTableModel modelTrata;

    public RegistroVisualizacionPersonasContagiadas() {
        initComponents();
        Extraer dataSQL = new Extraer();
        ArrayList<String> listas = dataSQL.denom_oms(dataSQL.variante());
        for (int i=0;i<listas.size();i++)
            desplegable_varianteM.addItem(listas.get(i));
        listas = dataSQL.nombCentro(dataSQL.CentroSaludHos());
        for (int i=0;i<listas.size();i++)
            desplegable_Centro.addItem(listas.get(i));
        for (int i=0;i<listas.size();i++)
            desplegable_Centro1.addItem(listas.get(i));
        crea.addTableHeaderPersonaContagiada(model,jTable_personasC);
        crea.addTableHeaderTratamientoPersonaC(model, jTable_tratamientos);
        crea.addTableHeaderHospitalPersonaC(model, jTable_hospital);
        bus.tableAllPersonaContagiada(jTable_personasC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_modificar = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        boton_cmbCedula = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_cmbVariante = new javax.swing.JButton();
        boton_cmbFecha = new javax.swing.JButton();
        boton_cmbTiempo = new javax.swing.JButton();
        boton_cmbTipo = new javax.swing.JButton();
        boton_cmbTratamiento = new javax.swing.JButton();
        boton_cmbCentro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JLabel_cedula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JLabel_fecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        boton_volverAMain = new javax.swing.JButton();
        jFrame_modificardoc = new javax.swing.JFrame();
        jPanel18 = new javax.swing.JPanel();
        boton_aggmodidoc = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        label_Doc = new javax.swing.JLabel();
        desplegable_NacionalidadM = new javax.swing.JComboBox<>();
        textField_NDocumentoM = new javax.swing.JTextField();
        title_persona2 = new javax.swing.JLabel();
        boton_volvermodidoc = new javax.swing.JButton();
        jFrame_modificarvariante = new javax.swing.JFrame();
        jPanel19 = new javax.swing.JPanel();
        boton_aggmodivar = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        label_Doc1 = new javax.swing.JLabel();
        desplegable_varianteM = new javax.swing.JComboBox<>();
        title_persona3 = new javax.swing.JLabel();
        boton_volvermodivar = new javax.swing.JButton();
        jFrame_fechanac = new javax.swing.JFrame();
        jPanel13 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDP1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        fechaNac = new com.toedter.calendar.JDateChooser();
        label_Fecha_contagio = new javax.swing.JLabel();
        label_Fecha_Nac4 = new javax.swing.JLabel();
        label_Fecha_contagio1 = new javax.swing.JLabel();
        title_persona = new javax.swing.JLabel();
        boton_Volver_RegistroDP2 = new javax.swing.JButton();
        jFrame_CentroSalud = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        boton_Volver_Centro = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        desplegable_Centro = new javax.swing.JComboBox<>();
        label_Denominacion2 = new javax.swing.JLabel();
        label_centrosalud = new javax.swing.JLabel();
        label_Denominacion4 = new javax.swing.JLabel();
        title_RegistroVariante1 = new javax.swing.JLabel();
        boton_Aceptar_Centro = new javax.swing.JButton();
        jFrame_CentroSaludNuevo = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        desplegable_Centro1 = new javax.swing.JComboBox<>();
        label_Denominacion5 = new javax.swing.JLabel();
        title_RegistroVariante2 = new javax.swing.JLabel();
        boton_Aceptar_CentroNuevo = new javax.swing.JButton();
        regisTratamiento = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        boton_Volver_TrataPac = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label_Denominacion = new javax.swing.JLabel();
        desplegable_Tratamientos = new javax.swing.JComboBox<>();
        boton_EliTrataPac = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableTrata = new javax.swing.JTable();
        boton_AggTrataPaciente = new javax.swing.JButton();
        boton_modificarEstadoTrata = new javax.swing.JButton();
        title_RegistroVariante = new javax.swing.JLabel();
        boton_Volver_TrataPac1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Volver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_Sintomas = new javax.swing.JLabel();
        desplegable_Nacionalidad = new javax.swing.JComboBox<>();
        boton_ModificarPersona = new javax.swing.JButton();
        boton_BusPersona = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_EliminarPersona = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        field_Numero_Doc1 = new javax.swing.JTextField();
        boton_AggPersona = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_personasC = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_tratamientos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_hospital = new javax.swing.JTable();
        title_RegistroSintomas = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(159, 211, 241));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_cmbCedula.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbCedula.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbCedula.setText("N° documento");
        boton_cmbCedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbCedulaActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 120, 100));

        boton_cmbVariante.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbVariante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbVariante.setText("Variante");
        boton_cmbVariante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbVarianteActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 150, 30));

        boton_cmbFecha.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbFecha.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbFecha.setText("Fecha de contagio");
        boton_cmbFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbFechaActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 150, 30));

        boton_cmbTiempo.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbTiempo.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbTiempo.setText("Tiempo de Reposo");
        boton_cmbTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbTiempoActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 150, 30));

        boton_cmbTipo.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbTipo.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbTipo.setText("Tipo");
        boton_cmbTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbTipoActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 150, 30));

        boton_cmbTratamiento.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbTratamiento.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbTratamiento.setText("Tratamientos");
        boton_cmbTratamiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbTratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbTratamientoActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 150, 30));

        boton_cmbCentro.setBackground(new java.awt.Color(235, 235, 235));
        boton_cmbCentro.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_cmbCentro.setText("Centro");
        boton_cmbCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_cmbCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cmbCentroActionPerformed(evt);
            }
        });
        jPanel8.add(boton_cmbCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 120, 100));

        JLabel_cedula.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        JLabel_cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(JLabel_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 180, 30));

        jLabel4.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cédula:");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 90, -1));

        jLabel7.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Modificación de Persona Contagiada ");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, -1));

        JLabel_fecha.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        JLabel_fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(JLabel_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 180, 30));

        jLabel9.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha:");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 70, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 770, 260));

        boton_volverAMain.setBackground(new java.awt.Color(235, 235, 235));
        boton_volverAMain.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_volverAMain.setText("Volver");
        boton_volverAMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_volverAMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverAMainActionPerformed(evt);
            }
        });
        jPanel7.add(boton_volverAMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 110, 30));

        Frame_modificar.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(159, 211, 241));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_aggmodidoc.setBackground(new java.awt.Color(235, 235, 235));
        boton_aggmodidoc.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_aggmodidoc.setText("Guardar");
        boton_aggmodidoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_aggmodidoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aggmodidocActionPerformed(evt);
            }
        });
        jPanel18.add(boton_aggmodidoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 80, 27));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Doc.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Doc.setText("Documento de identidad: ");
        jPanel21.add(label_Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        desplegable_NacionalidadM.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_NacionalidadM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        desplegable_NacionalidadM.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_NacionalidadM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_NacionalidadMActionPerformed(evt);
            }
        });
        jPanel21.add(desplegable_NacionalidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 50, -1));

        textField_NDocumentoM.setBackground(new java.awt.Color(235, 235, 235));
        textField_NDocumentoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField_NDocumentoMActionPerformed(evt);
            }
        });
        jPanel21.add(textField_NDocumentoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 160, -1));

        jPanel18.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 480, 90));

        title_persona2.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona2.setText("Cambio de numero de documento");
        jPanel18.add(title_persona2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 540, 40));

        boton_volvermodidoc.setBackground(new java.awt.Color(235, 235, 235));
        boton_volvermodidoc.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_volvermodidoc.setText("Volver");
        boton_volvermodidoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_volvermodidoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volvermodidocActionPerformed(evt);
            }
        });
        jPanel18.add(boton_volvermodidoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, 27));

        jFrame_modificardoc.getContentPane().add(jPanel18, java.awt.BorderLayout.CENTER);

        jPanel19.setBackground(new java.awt.Color(159, 211, 241));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_aggmodivar.setBackground(new java.awt.Color(235, 235, 235));
        boton_aggmodivar.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_aggmodivar.setText("Guardar");
        boton_aggmodivar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_aggmodivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aggmodivarActionPerformed(evt);
            }
        });
        jPanel19.add(boton_aggmodivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 27));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Doc1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Doc1.setText("Variantes:");
        jPanel22.add(label_Doc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        desplegable_varianteM.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_varianteM.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_varianteM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                desplegable_varianteMMouseClicked(evt);
            }
        });
        desplegable_varianteM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_varianteMActionPerformed(evt);
            }
        });
        jPanel22.add(desplegable_varianteM, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, -1));

        jPanel19.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 390, 90));

        title_persona3.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona3.setText("Cambio de variante");
        jPanel19.add(title_persona3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 40));

        boton_volvermodivar.setBackground(new java.awt.Color(235, 235, 235));
        boton_volvermodivar.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_volvermodivar.setText("Volver");
        boton_volvermodivar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_volvermodivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volvermodivarActionPerformed(evt);
            }
        });
        jPanel19.add(boton_volvermodivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, 27));

        jFrame_modificarvariante.getContentPane().add(jPanel19, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(159, 211, 241));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDP1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDP1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDP1.setText("Guardar");
        boton_Siguiente_RegistroDP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDP1ActionPerformed(evt);
            }
        });
        jPanel13.add(boton_Siguiente_RegistroDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, 27));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(fechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 180, -1));

        label_Fecha_contagio.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_contagio.setText("00/00/0000");
        jPanel14.add(label_Fecha_contagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        label_Fecha_Nac4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac4.setText("Nueva fecha de contagio: ");
        jPanel14.add(label_Fecha_Nac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_Fecha_contagio1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_contagio1.setText("Fecha de contagio actual: ");
        jPanel14.add(label_Fecha_contagio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 430, 90));

        title_persona.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona.setText("Nueva fecha de contagio");
        jPanel13.add(title_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 400, 40));

        boton_Volver_RegistroDP2.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP2.setText("Volver");
        boton_Volver_RegistroDP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP2ActionPerformed(evt);
            }
        });
        jPanel13.add(boton_Volver_RegistroDP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, 27));

        jFrame_fechanac.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(159, 211, 241));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver_Centro.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_Centro.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_Centro.setText("Volver");
        boton_Volver_Centro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_CentroActionPerformed(evt);
            }
        });
        jPanel5.add(boton_Volver_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 80, 27));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desplegable_Centro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Centro.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_CentroActionPerformed(evt);
            }
        });
        jPanel6.add(desplegable_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 240, -1));

        label_Denominacion2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion2.setText("Centro de hospitalización anterior:");
        jPanel6.add(label_Denominacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        label_centrosalud.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_centrosalud.setText("Centro salud:");
        jPanel6.add(label_centrosalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 210, -1));

        label_Denominacion4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion4.setText("Centro de hospitalización: ");
        jPanel6.add(label_Denominacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 520, 110));

        title_RegistroVariante1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroVariante1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroVariante1.setText("Modificar centro de hospitalización");
        jPanel5.add(title_RegistroVariante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, 40));

        boton_Aceptar_Centro.setBackground(new java.awt.Color(235, 235, 235));
        boton_Aceptar_Centro.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Aceptar_Centro.setText("Aceptar");
        boton_Aceptar_Centro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Aceptar_Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Aceptar_CentroActionPerformed(evt);
            }
        });
        jPanel5.add(boton_Aceptar_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 80, 27));

        jFrame_CentroSalud.getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel9.setBackground(new java.awt.Color(159, 211, 241));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desplegable_Centro1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Centro1.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Centro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_Centro1ActionPerformed(evt);
            }
        });
        jPanel10.add(desplegable_Centro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 240, -1));

        label_Denominacion5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion5.setText("Centro de hospitalización: ");
        jPanel10.add(label_Denominacion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 520, 70));

        title_RegistroVariante2.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroVariante2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroVariante2.setText("Seleccionar centro de hospitalización");
        jPanel9.add(title_RegistroVariante2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 580, 40));

        boton_Aceptar_CentroNuevo.setBackground(new java.awt.Color(235, 235, 235));
        boton_Aceptar_CentroNuevo.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Aceptar_CentroNuevo.setText("Aceptar");
        boton_Aceptar_CentroNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Aceptar_CentroNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Aceptar_CentroNuevoActionPerformed(evt);
            }
        });
        jPanel9.add(boton_Aceptar_CentroNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 80, 27));

        jFrame_CentroSaludNuevo.getContentPane().add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(159, 211, 241));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver_TrataPac.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_TrataPac.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_TrataPac.setText("Volver");
        boton_Volver_TrataPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_TrataPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_TrataPacActionPerformed(evt);
            }
        });
        jPanel3.add(boton_Volver_TrataPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 27));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Denominacion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion.setText("Tratamientos:");
        jPanel4.add(label_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        desplegable_Tratamientos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Tratamientos.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Tratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_TratamientosActionPerformed(evt);
            }
        });
        jPanel4.add(desplegable_Tratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, -1));

        boton_EliTrataPac.setBackground(new java.awt.Color(235, 235, 235));
        boton_EliTrataPac.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_EliTrataPac.setText("Eliminar");
        boton_EliTrataPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_EliTrataPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EliTrataPacActionPerformed(evt);
            }
        });
        jPanel4.add(boton_EliTrataPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 110, 27));

        TableTrata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableTrata);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 270, 110));

        boton_AggTrataPaciente.setBackground(new java.awt.Color(235, 235, 235));
        boton_AggTrataPaciente.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_AggTrataPaciente.setText("Agregar");
        boton_AggTrataPaciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_AggTrataPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AggTrataPacienteActionPerformed(evt);
            }
        });
        jPanel4.add(boton_AggTrataPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 27));

        boton_modificarEstadoTrata.setBackground(new java.awt.Color(235, 235, 235));
        boton_modificarEstadoTrata.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_modificarEstadoTrata.setText("Modificar Estado");
        boton_modificarEstadoTrata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_modificarEstadoTrata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarEstadoTrataActionPerformed(evt);
            }
        });
        jPanel4.add(boton_modificarEstadoTrata, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, 27));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 410, 250));

        title_RegistroVariante.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroVariante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroVariante.setText("Modificar tratamientos");
        jPanel3.add(title_RegistroVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 40));

        boton_Volver_TrataPac1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_TrataPac1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_TrataPac1.setText("Volver");
        boton_Volver_TrataPac1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_TrataPac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_TrataPac1ActionPerformed(evt);
            }
        });
        jPanel3.add(boton_Volver_TrataPac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 27));

        regisTratamiento.getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver.setText("Volver");
        boton_Volver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 80, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Sintomas.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Sintomas.setText("Personas contagiadas: ");
        jPanel2.add(label_Sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        desplegable_Nacionalidad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Nacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        desplegable_Nacionalidad.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Nacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_NacionalidadActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, -1));

        boton_ModificarPersona.setBackground(new java.awt.Color(235, 235, 235));
        boton_ModificarPersona.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_ModificarPersona.setText("Modificar");
        boton_ModificarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_ModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ModificarPersonaActionPerformed(evt);
            }
        });
        jPanel2.add(boton_ModificarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 90, 27));

        boton_BusPersona.setBackground(new java.awt.Color(235, 235, 235));
        boton_BusPersona.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_BusPersona.setText("Buscar");
        boton_BusPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_BusPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BusPersonaActionPerformed(evt);
            }
        });
        jPanel2.add(boton_BusPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 90, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 130, 100));

        boton_EliminarPersona.setBackground(new java.awt.Color(235, 235, 235));
        boton_EliminarPersona.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_EliminarPersona.setText("Eliminar");
        boton_EliminarPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_EliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EliminarPersonaActionPerformed(evt);
            }
        });
        jPanel2.add(boton_EliminarPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 90, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 130, 100));

        field_Numero_Doc1.setBackground(new java.awt.Color(235, 235, 235));
        field_Numero_Doc1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                field_Numero_Doc1ComponentAdded(evt);
            }
        });
        field_Numero_Doc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Numero_Doc1ActionPerformed(evt);
            }
        });
        jPanel2.add(field_Numero_Doc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 300, -1));

        boton_AggPersona.setBackground(new java.awt.Color(235, 235, 235));
        boton_AggPersona.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_AggPersona.setText("Agregar");
        boton_AggPersona.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_AggPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AggPersonaActionPerformed(evt);
            }
        });
        jPanel2.add(boton_AggPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 90, 27));

        jTable_personasC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_personasC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_personasCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_personasC);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 600, 180));

        jTable_tratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_tratamientos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 300, 130));

        jTable_hospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_hospital);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 300, 130));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 850, 460));

        title_RegistroSintomas.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroSintomas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroSintomas.setText("Personas contagiadas");
        jPanel1.add(title_RegistroSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 850, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VolverActionPerformed
        Proceso2 pro = new Proceso2();
        crea.InterfazDiferentes(this, pro, 695, 430);
    }//GEN-LAST:event_boton_VolverActionPerformed

    private void boton_ModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ModificarPersonaActionPerformed
        if (jTable_personasC.getSelectedRow()!= -1)
        {
            model = (DefaultTableModel) jTable_personasC.getModel();
            
            JLabel_cedula.setText(model.getValueAt(jTable_personasC.getSelectedRow(), 1).toString());
            JLabel_fecha.setText(model.getValueAt(jTable_personasC.getSelectedRow(), 2).toString());
            if(model.getValueAt(jTable_personasC.getSelectedRow(), 4).toString().equals("En casa")){
                boton_cmbCentro.setEnabled(false);
            }
            crea.InterfazIguales(this, Frame_modificar, 840, 379);
        }else
            JOptionPane.showMessageDialog(null, "Debe seleccionar en la tabla la persona a modificar","Aviso",INFORMATION_MESSAGE);
    }//GEN-LAST:event_boton_ModificarPersonaActionPerformed

    private void boton_BusPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BusPersonaActionPerformed
        Verificador veri = new Verificador();
        if (veri.dataNB(field_Numero_Doc1)){
            if (field_Numero_Doc1.getText().toString().matches("-?\\d+")){
                bus.limpiarTabla(jTable_hospital);
                bus.limpiarTabla(jTable_tratamientos);
                bus.limpiarTabla(jTable_personasC);
                bus.tablePersonaContagiadaxCedula(jTable_personasC, desplegable_Nacionalidad.getSelectedItem().toString()+field_Numero_Doc1.getText().toString());
            }else
                JOptionPane.showMessageDialog(null, "La cedula debe ser numeros enteros","Error",ERROR_MESSAGE);
        }else{
            bus.limpiarTabla(jTable_hospital);
            bus.limpiarTabla(jTable_tratamientos);
            bus.limpiarTabla(jTable_personasC);
            bus.tableAllPersonaContagiada(jTable_personasC);
        }
        field_Numero_Doc1.setText("");
    }//GEN-LAST:event_boton_BusPersonaActionPerformed

    private void boton_EliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EliminarPersonaActionPerformed
        model = (DefaultTableModel) jTable_personasC.getModel();
        bus.limpiarTabla(jTable_hospital);
        bus.limpiarTabla(jTable_tratamientos);
        if (jTable_personasC.getSelectedRow() != -1){
            bus.EliminarPacienteContagio(model.getValueAt(jTable_personasC.getSelectedRow(),1).toString(), model.getValueAt(jTable_personasC.getSelectedRow(),2).toString());
            bus.EliminarPaciente(model.getValueAt(jTable_personasC.getSelectedRow(),1).toString());
            JOptionPane.showMessageDialog(null, "Eliminada exitosamente");
            bus.limpiarTabla(jTable_personasC);
            bus.tableAllPersonaContagiada(jTable_personasC);
        }else
            JOptionPane.showMessageDialog(null, "Debe seleccionar una persona para ser eliminada","Aviso",INFORMATION_MESSAGE);
    }//GEN-LAST:event_boton_EliminarPersonaActionPerformed

    private void desplegable_NacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_NacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_NacionalidadActionPerformed

    private void field_Numero_Doc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Numero_Doc1ActionPerformed
        
    }//GEN-LAST:event_field_Numero_Doc1ActionPerformed

    private void field_Numero_Doc1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_field_Numero_Doc1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Numero_Doc1ComponentAdded

    private void boton_AggPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AggPersonaActionPerformed
        registrarPersonaContagiada regisPer = new registrarPersonaContagiada();
        crea.InterfazDiferentes(this, regisPer, 542, 448);
    }//GEN-LAST:event_boton_AggPersonaActionPerformed

    private void jTable_personasCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_personasCMouseClicked
        model = (DefaultTableModel) jTable_personasC.getModel();
        String CI = model.getValueAt(jTable_personasC.getSelectedRow(), 1).toString();
        String fecha = model.getValueAt(jTable_personasC.getSelectedRow(), 2).toString();
        bus.limpiarTabla(jTable_tratamientos);
        bus.limpiarTabla(jTable_hospital);
        bus.tableTratamientoPersonaC(jTable_tratamientos,CI,fecha);
        bus.tableHospitalPersonaC(CI,jTable_hospital,fecha);
    }//GEN-LAST:event_jTable_personasCMouseClicked

    private void boton_cmbCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbCedulaActionPerformed
        crea.InterfazIguales(Frame_modificar, jFrame_modificardoc, 554, 241);
    }//GEN-LAST:event_boton_cmbCedulaActionPerformed

    private void boton_cmbVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbVarianteActionPerformed
        crea.InterfazIguales(Frame_modificar, jFrame_modificarvariante, 465, 238);
    }//GEN-LAST:event_boton_cmbVarianteActionPerformed

    private void boton_cmbFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbFechaActionPerformed
        fechaNac.getDateEditor().setEnabled(false);
        fechaNac.getJCalendar().setMaxSelectableDate(new Date());
        fechaNac.setDate(new Date(System.currentTimeMillis()));
        label_Fecha_contagio.setText(JLabel_fecha.getText());
        crea.InterfazIguales(Frame_modificar, jFrame_fechanac,499, 241);
    }//GEN-LAST:event_boton_cmbFechaActionPerformed

    private void boton_cmbTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbTiempoActionPerformed
        Verificador veri = new Verificador();
        Buscador bus = new Buscador();
        String dias = bus.tiempoPacCedula(JLabel_cedula.getText(), JLabel_fecha.getText());
        String dato = JOptionPane.showInputDialog("El tiempo de reposo es: "+dias+". Ingrese el nuevo tiempo de reposo");
        if(dato != null){
            if((veri.dataNBS(dato))||(veri.noVacio(dato))){
                if(dato.matches("-?\\d+")){
                    Guardar insertSQL = new Guardar();
                    if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(), dato,3)){
                        JOptionPane.showMessageDialog(null, "Se ha modificado el tiempo de reposo correctamente \nAnterior: "+dias+" \nNuevo: "+dato+" días");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"La informacion en los campos numericos no es valida","Error",ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "No se admiten casillas con unicamente espacios en blanco","Error",ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_boton_cmbTiempoActionPerformed

    private void boton_cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbTipoActionPerformed
        model = (DefaultTableModel) jTable_personasC.getModel();
        Buscador bus = new Buscador();
        if(bus.tipoPersonaFecha(JLabel_cedula.getText(), JLabel_fecha.getText()).equals("t")){
            Guardar insertSQL = new Guardar();
            if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(), "F",6)){
                bus.EliminarHospitales(JLabel_cedula.getText(), JLabel_fecha.getText());
                JOptionPane.showMessageDialog(null, "Se ha modificado el tipo de reposo correctamente \nAnterior: Hospitalizado \nNuevo: En casa");
                boton_cmbCentro.setEnabled(false);
            }
        }else{
            Guardar insertSQL = new Guardar();
            if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(), "T",6)){
                JOptionPane.showMessageDialog(null, "Se ha modificado el tipo de reposo correctamente \nAnterior: En casa \nNuevo: Hospitalizado");
                boton_cmbCentro.setEnabled(true);
                crea.InterfazIguales(Frame_modificar, jFrame_CentroSaludNuevo, 594, 222);
            }
        }
    }//GEN-LAST:event_boton_cmbTipoActionPerformed

    private void boton_cmbTratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbTratamientoActionPerformed
        ArrayList<String> listas = dataSQL.codigoTratamientos(dataSQL.TratamientoPaciente());
        desplegable_Tratamientos.removeAllItems();
        for (int i=0;i<listas.size();i++)
            desplegable_Tratamientos.addItem(listas.get(i));
        bus.limpiarTabla(TableTrata);
        String CI = JLabel_cedula.getText();
        String fecha = JLabel_fecha.getText();
        crea.addTableHeaderTratamientoPersonaC(model, TableTrata);
        bus.tableTratamientoPersonaC(TableTrata,CI, fecha);
        crea.InterfazIguales(Frame_modificar, regisTratamiento, 484, 398); 
    }//GEN-LAST:event_boton_cmbTratamientoActionPerformed

    private void boton_cmbCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cmbCentroActionPerformed
        Buscador bus = new Buscador();
        label_centrosalud.setText(bus.personaCodHospital(JLabel_cedula.getText(), JLabel_fecha.getText()));
        crea.InterfazIguales(Frame_modificar, jFrame_CentroSalud, 593, 263);
    }//GEN-LAST:event_boton_cmbCentroActionPerformed

    private void boton_volverAMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverAMainActionPerformed
        bus.limpiarTabla(jTable_hospital);
        bus.limpiarTabla(jTable_tratamientos);
        bus.limpiarTabla(jTable_personasC);
        bus.tableAllPersonaContagiada(jTable_personasC);
        crea.InterfazIguales(Frame_modificar, this, 942, 616);
    }//GEN-LAST:event_boton_volverAMainActionPerformed

    private void boton_aggmodidocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aggmodidocActionPerformed
        Guardar insertSQL = new Guardar();
        Verificador veri = new Verificador();
        if(veri.dataNB(textField_NDocumentoM)){
            if(veri.noVacio(textField_NDocumentoM.getText().toString())){
                if(textField_NDocumentoM.getText().toString().matches("-?\\d+")){
                    if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(), desplegable_NacionalidadM.getSelectedItem().toString()+textField_NDocumentoM.getText().toString(),1)){
                        JOptionPane.showMessageDialog(null, "Se ha modificado la cedula correctamente \nAnterior: "+JLabel_cedula.getText()+" \nNuevo: "+desplegable_NacionalidadM.getSelectedItem().toString()+textField_NDocumentoM.getText().toString());
                        JLabel_cedula.setText(desplegable_NacionalidadM.getSelectedItem().toString()+textField_NDocumentoM.getText().toString());
                        textField_NDocumentoM.setText("");
                        crea.InterfazIguales(jFrame_modificardoc, Frame_modificar, 840, 379);
                    }else
                        textField_NDocumentoM.setText("");
                }else{
                    JOptionPane.showMessageDialog(null,"La informacion en los campos numericos no es valida","Error",ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "No se admiten casillas con unicamente espacios en blanco","Error",ERROR_MESSAGE);
            }
        }else
            JOptionPane.showMessageDialog(null, "Se encuentran casillas sin rellenar","Error",ERROR_MESSAGE);
        
    }//GEN-LAST:event_boton_aggmodidocActionPerformed

    private void boton_volvermodidocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volvermodidocActionPerformed
        crea.InterfazIguales(jFrame_modificardoc, Frame_modificar,840, 379);
    }//GEN-LAST:event_boton_volvermodidocActionPerformed

    private void desplegable_NacionalidadMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_NacionalidadMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_NacionalidadMActionPerformed

    private void textField_NDocumentoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField_NDocumentoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField_NDocumentoMActionPerformed

    private void boton_aggmodivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aggmodivarActionPerformed
        Guardar insertSQL = new Guardar();
        Buscador bus = new Buscador();
        String variante = bus.variantePacCedula(JLabel_cedula.getText(), JLabel_fecha.getText());
        if(!variante.equals(desplegable_varianteM.getSelectedItem().toString())){
            if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(), desplegable_varianteM.getSelectedItem().toString(),2)){
                JOptionPane.showMessageDialog(null, "Se ha modificado la variante correctamente \nAnterior: "+variante+" \nNueva: "+desplegable_varianteM.getSelectedItem().toString());
                crea.InterfazIguales(jFrame_modificarvariante, Frame_modificar, 840, 379); 
            
            }
        }else
            JOptionPane.showMessageDialog(null, "La variante seleccionada es igual a la existente","Aviso",INFORMATION_MESSAGE);
    }//GEN-LAST:event_boton_aggmodivarActionPerformed

    private void desplegable_varianteMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_varianteMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_varianteMActionPerformed

    private void boton_volvermodivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volvermodivarActionPerformed
        bus.limpiarTabla(jTable_hospital);
        bus.limpiarTabla(jTable_tratamientos);
        bus.limpiarTabla(jTable_personasC);
        bus.tableAllPersonaContagiada(jTable_personasC);
        crea.InterfazIguales(jFrame_modificarvariante, Frame_modificar,840, 379);
    }//GEN-LAST:event_boton_volvermodivarActionPerformed

    private void boton_Siguiente_RegistroDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDP1ActionPerformed
        Date date = fechaNac.getDate();
        long da = date.getTime();
        java.sql.Date fecha = new java.sql.Date(da);
        Guardar insertSQL = new Guardar();
        if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(),fecha.toString(),4)){
            JOptionPane.showMessageDialog(null, "Se ha modificado la fecha correctamente \nAnterior: "+JLabel_fecha.getText()+" \nNueva: "+fecha.toString());
            JLabel_fecha.setText(fecha.toString());
            crea.InterfazIguales(jFrame_fechanac, Frame_modificar, 840, 379);
        }
    }//GEN-LAST:event_boton_Siguiente_RegistroDP1ActionPerformed

    private void boton_Volver_RegistroDP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP2ActionPerformed
        crea.InterfazIguales(jFrame_fechanac, Frame_modificar, 840, 379);
    }//GEN-LAST:event_boton_Volver_RegistroDP2ActionPerformed

    private void boton_Volver_CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_CentroActionPerformed
        crea.InterfazIguales(jFrame_CentroSalud, Frame_modificar,840, 379);
    }//GEN-LAST:event_boton_Volver_CentroActionPerformed

    private void desplegable_CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_CentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_CentroActionPerformed

    private void boton_Aceptar_CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Aceptar_CentroActionPerformed
        Guardar insertSQL = new Guardar();
        Buscador bus = new Buscador();
        if(!label_centrosalud.getText().toString().equals(desplegable_Centro.getSelectedItem().toString())){
            if(insertSQL.ModiPacienteC(JLabel_cedula.getText(), JLabel_fecha.getText(),bus.codCentro(desplegable_Centro.getSelectedItem().toString()),5)){
                JOptionPane.showMessageDialog(null, "Se ha modificado el centro de hospitalización correctamente \nAnterior: "+label_centrosalud.getText().toString()+" \nNuevo: "+desplegable_Centro.getSelectedItem().toString());
                crea.InterfazIguales(jFrame_CentroSalud, Frame_modificar, 840, 379);
            }
        }else{
            JOptionPane.showMessageDialog(null, "El centro seleccionado es igual al existente, por favor escoja otra opción","Aviso",INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_boton_Aceptar_CentroActionPerformed

    private void desplegable_Centro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_Centro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_Centro1ActionPerformed

    private void boton_Aceptar_CentroNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Aceptar_CentroNuevoActionPerformed
        Guardar insertSQL = new Guardar();
        if(insertSQL.hospitalizado(JLabel_cedula.getText(), bus.codCentro(desplegable_Centro1.getSelectedItem().toString()), JLabel_fecha.getText())){
            JOptionPane.showMessageDialog(null, "El centro de hospitalización fue registrado exitosamente");
            crea.InterfazIguales(jFrame_CentroSaludNuevo, Frame_modificar, 840, 379);
        }
    }//GEN-LAST:event_boton_Aceptar_CentroNuevoActionPerformed

    private void boton_Volver_TrataPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_TrataPacActionPerformed
        crea.InterfazIguales(regisTratamiento, Frame_modificar, 840, 379);
    }//GEN-LAST:event_boton_Volver_TrataPacActionPerformed

    private void desplegable_TratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_TratamientosActionPerformed

    }//GEN-LAST:event_desplegable_TratamientosActionPerformed

    private void boton_EliTrataPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EliTrataPacActionPerformed
        modelTrata = (DefaultTableModel) TableTrata.getModel();
        if (TableTrata.getSelectedRow() != -1){
            if(bus.tipoPersonaFecha(JLabel_cedula.getText(), JLabel_fecha.getText()).equals("f") || ((bus.tipoPersonaFecha(JLabel_cedula.getText(), JLabel_fecha.getText()).equals("t")) && (modelTrata.getRowCount()>1))){
                bus.trataPacEli(JLabel_cedula.getText(), JLabel_fecha.getText(), modelTrata.getValueAt(TableTrata.getSelectedRow(), 0).toString());
                modelTrata.removeRow(TableTrata.getSelectedRow());
            }
            else{
                JOptionPane.showMessageDialog(null, "El paciente, es de tipo Hospitalizado, por lo tanto, no puede quedar sin tratamientos","Warning",WARNING_MESSAGE);
            }
        }    
        else
            JOptionPane.showMessageDialog(null, "No ha seleccionado un tratamiento a eliminar","Warning",WARNING_MESSAGE);
    }//GEN-LAST:event_boton_EliTrataPacActionPerformed

    private void boton_AggTrataPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AggTrataPacienteActionPerformed
        Verificador veri = new Verificador();
        modelTrata = (DefaultTableModel) TableTrata.getModel();
        String dato;
        dato = desplegable_Tratamientos.getSelectedItem().toString();
        if (!veri.existenciaTable(modelTrata, dato)) {
            Buscador bus = new Buscador();
            modelTrata.addRow(new Object[]{dato,bus.DescripTrataPac(dato),"En curso"});
            Guardar insertSQL = new Guardar();
            insertSQL.requiere(JLabel_cedula.getText(),dato, JLabel_fecha.getText(),"En curso");
        }
    }//GEN-LAST:event_boton_AggTrataPacienteActionPerformed

    private void boton_Volver_TrataPac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_TrataPac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_TrataPac1ActionPerformed

    private void desplegable_varianteMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_desplegable_varianteMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_varianteMMouseClicked

    private void boton_modificarEstadoTrataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarEstadoTrataActionPerformed
        modelTrata = (DefaultTableModel) TableTrata.getModel();
        Guardar insertSQL = new Guardar();
        if (TableTrata.getSelectedRow() != -1){
            if(modelTrata.getValueAt(TableTrata.getSelectedRow(), 2).toString().equals("En curso")){
                insertSQL.cambiarEstado(JLabel_cedula.getText(), JLabel_fecha.getText(), modelTrata.getValueAt(TableTrata.getSelectedRow(), 0).toString(), "Finalizado");
                JOptionPane.showMessageDialog(null, "Se ha modificado el Estado del Tratamiento '"+modelTrata.getValueAt(TableTrata.getSelectedRow(), 0).toString()+"' a 'Finalizado' correctamente");
            }else{
                insertSQL.cambiarEstado(JLabel_cedula.getText(), JLabel_fecha.getText(), modelTrata.getValueAt(TableTrata.getSelectedRow(), 0).toString(), "En curso");
                JOptionPane.showMessageDialog(null, "Se ha modificado el Estado del Tratamiento '"+modelTrata.getValueAt(TableTrata.getSelectedRow(), 0).toString()+"' a 'En curso' correctamente");
            }
        }    
        else
            JOptionPane.showMessageDialog(null, "No ha seleccionado un tratamiento a modificar","Warning",WARNING_MESSAGE);
    }//GEN-LAST:event_boton_modificarEstadoTrataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionPersonasContagiadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionPersonasContagiadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionPersonasContagiadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionPersonasContagiadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVisualizacionPersonasContagiadas().setVisible(true);
            }
        });
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Frame_modificar;
    private javax.swing.JLabel JLabel_cedula;
    private javax.swing.JLabel JLabel_fecha;
    private javax.swing.JTable TableTrata;
    private javax.swing.JButton boton_Aceptar_Centro;
    private javax.swing.JButton boton_Aceptar_CentroNuevo;
    private javax.swing.JButton boton_AggPersona;
    private javax.swing.JButton boton_AggTrataPaciente;
    private javax.swing.JButton boton_BusPersona;
    private javax.swing.JButton boton_EliTrataPac;
    private javax.swing.JButton boton_EliminarPersona;
    private javax.swing.JButton boton_ModificarPersona;
    private javax.swing.JButton boton_Siguiente_RegistroDP1;
    private javax.swing.JButton boton_Volver;
    private javax.swing.JButton boton_Volver_Centro;
    private javax.swing.JButton boton_Volver_RegistroDP2;
    private javax.swing.JButton boton_Volver_TrataPac;
    private javax.swing.JButton boton_Volver_TrataPac1;
    private javax.swing.JButton boton_aggmodidoc;
    private javax.swing.JButton boton_aggmodivar;
    private javax.swing.JButton boton_cmbCedula;
    private javax.swing.JButton boton_cmbCentro;
    private javax.swing.JButton boton_cmbFecha;
    private javax.swing.JButton boton_cmbTiempo;
    private javax.swing.JButton boton_cmbTipo;
    private javax.swing.JButton boton_cmbTratamiento;
    private javax.swing.JButton boton_cmbVariante;
    private javax.swing.JButton boton_modificarEstadoTrata;
    private javax.swing.JButton boton_volverAMain;
    private javax.swing.JButton boton_volvermodidoc;
    private javax.swing.JButton boton_volvermodivar;
    private javax.swing.JComboBox<String> desplegable_Centro;
    private javax.swing.JComboBox<String> desplegable_Centro1;
    private javax.swing.JComboBox<String> desplegable_Nacionalidad;
    private javax.swing.JComboBox<String> desplegable_NacionalidadM;
    private javax.swing.JComboBox<String> desplegable_Tratamientos;
    private javax.swing.JComboBox<String> desplegable_varianteM;
    private com.toedter.calendar.JDateChooser fechaNac;
    private javax.swing.JTextField field_Numero_Doc1;
    private javax.swing.JFrame jFrame_CentroSalud;
    private javax.swing.JFrame jFrame_CentroSaludNuevo;
    private javax.swing.JFrame jFrame_fechanac;
    private javax.swing.JFrame jFrame_modificardoc;
    private javax.swing.JFrame jFrame_modificarvariante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_hospital;
    private javax.swing.JTable jTable_personasC;
    private javax.swing.JTable jTable_tratamientos;
    private javax.swing.JLabel label_Denominacion;
    private javax.swing.JLabel label_Denominacion2;
    private javax.swing.JLabel label_Denominacion4;
    private javax.swing.JLabel label_Denominacion5;
    private javax.swing.JLabel label_Doc;
    private javax.swing.JLabel label_Doc1;
    private javax.swing.JLabel label_Fecha_Nac4;
    private javax.swing.JLabel label_Fecha_contagio;
    private javax.swing.JLabel label_Fecha_contagio1;
    private javax.swing.JLabel label_Sintomas;
    private javax.swing.JLabel label_centrosalud;
    private javax.swing.JFrame regisTratamiento;
    private javax.swing.JTextField textField_NDocumentoM;
    private javax.swing.JLabel title_RegistroSintomas;
    private javax.swing.JLabel title_RegistroVariante;
    private javax.swing.JLabel title_RegistroVariante1;
    private javax.swing.JLabel title_RegistroVariante2;
    private javax.swing.JLabel title_persona;
    private javax.swing.JLabel title_persona2;
    private javax.swing.JLabel title_persona3;
    // End of variables declaration//GEN-END:variables
}
