/*
 * To change this license header, choose License Headers in Project Properties.
 * ¿To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarMedicamento() {
        initComponents();
        this.setSize(545,350);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Volver_RegistroMed = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_imagen = new javax.swing.JLabel();
        label_Concentracion = new javax.swing.JLabel();
        label_NombreMed = new javax.swing.JLabel();
        field_Compuesto = new java.awt.TextField();
        field_NombreMed = new java.awt.TextField();
        label_Compuesto = new javax.swing.JLabel();
        field_Concentracion = new java.awt.TextField();
        title_medicamento = new javax.swing.JLabel();
        boton_Siguiente_RegistroMed = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver_RegistroMed.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroMed.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroMed.setText("Volver");
        boton_Volver_RegistroMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroMedActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/flo 1.png"))); // NOI18N
        jPanel2.add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 154, 110));

        label_Concentracion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Concentracion.setText("Concentración:");
        jPanel2.add(label_Concentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        label_NombreMed.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_NombreMed.setText("Nombre del medicamento: ");
        jPanel2.add(label_NombreMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        field_Compuesto.setBackground(new java.awt.Color(235, 235, 235));
        field_Compuesto.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_Compuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, -1));

        field_NombreMed.setBackground(new java.awt.Color(235, 235, 235));
        field_NombreMed.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_NombreMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 180, -1));

        label_Compuesto.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Compuesto.setText("Compuesto:");
        jPanel2.add(label_Compuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        field_Concentracion.setBackground(new java.awt.Color(235, 235, 235));
        field_Concentracion.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_Concentracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 200));

        title_medicamento.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_medicamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_medicamento.setText("Registro de medicamentos");
        jPanel1.add(title_medicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        boton_Siguiente_RegistroMed.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroMed.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroMed.setText("Aceptar");
        boton_Siguiente_RegistroMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroMedActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 80, 27));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroMedActionPerformed

    private void boton_Siguiente_RegistroMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_RegistroMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Siguiente_RegistroMed;
    private javax.swing.JButton boton_Volver_RegistroMed;
    private java.awt.TextField field_Compuesto;
    private java.awt.TextField field_Concentracion;
    private java.awt.TextField field_NombreMed;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Compuesto;
    private javax.swing.JLabel label_Concentracion;
    private javax.swing.JLabel label_NombreMed;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel title_medicamento;
    // End of variables declaration//GEN-END:variables
}
