/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import SQL.Extraer;
import SQL.Guardar;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableModel;
import tools.Buscador;
import tools.Creador;
import tools.Verificador;

/**
 *
 * @author Ricardo Fanghella
 */
public class RegistroVisualizacionVariante extends javax.swing.JFrame {
    Buscador bus = new Buscador();
    Creador crea = new Creador();
    DefaultTableModel model;
    Extraer dataSQL = new Extraer();
    

    public RegistroVisualizacionVariante() {
        initComponents();
        crea.Interfaz(this, 1008, 550);
        Creador creaInterfaz = new Creador();
       //crea.addTableHeaderPerRes(model, jTable_sintomas);
        crea.addTableHeaderVar(model,jTable_variantes);
        //crea.addTableHeaderEnfer(model, jTable_enfermedades);
        crea.addTableHeaderVarSint(model, jTable_sintomas);
        bus.tableAllvariantes(jTable_variantes);
        /*fechaNac.getDateEditor().setEnabled(false);
        fechaNac.getJCalendar().setMaxSelectableDate(new Date());
        fechaNac.setDate(new Date(System.currentTimeMillis()));*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        field_TiempoReposo = new javax.swing.JTextField();
        Frame_modificar = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        boton_linaje = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_forg = new javax.swing.JButton();
        boton_clasificacion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JLabel_cedula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_sintomas = new javax.swing.JButton();
        boton_volverAMain = new javax.swing.JButton();
        jFrame_fechaorigen = new javax.swing.JFrame();
        jPanel13 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDP1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        label_Fecha_Org3 = new com.toedter.calendar.JDateChooser();
        label_Fecha_Nac3 = new javax.swing.JLabel();
        title_persona = new javax.swing.JLabel();
        boton_Volver_RegistroDP2 = new javax.swing.JButton();
        jFrame_clasificacion = new javax.swing.JFrame();
        jPanel15 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDP2 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        label_Fecha_Nac4 = new javax.swing.JLabel();
        desplegable_clasificacion = new javax.swing.JComboBox<>();
        title_persona1 = new javax.swing.JLabel();
        boton_Volver_RegistroDP3 = new javax.swing.JButton();
        jFrame_Sintomas = new javax.swing.JFrame();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        label_Denominacion = new javax.swing.JLabel();
        desplegable_Sintomas = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        TableSint = new javax.swing.JTable();
        boton_VerSintomas1 = new javax.swing.JButton();
        boton_VerSintomas = new javax.swing.JButton();
        title_persona4 = new javax.swing.JLabel();
        boton_Volver_RegistroDP6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Volver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_VariantesRegistradas = new javax.swing.JLabel();
        boton_ModificarVariante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_variantes = new javax.swing.JTable();
        boton_BusVariante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_EliminarVariante = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        field_Denominacion = new javax.swing.JTextField();
        boton_AggVariante = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_sintomas = new javax.swing.JTable();
        title_RegistroSintomas = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        field_TiempoReposo.setBackground(new java.awt.Color(235, 235, 235));
        field_TiempoReposo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_TiempoReposoActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(159, 211, 241));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_linaje.setBackground(new java.awt.Color(235, 235, 235));
        boton_linaje.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_linaje.setText("Linaje");
        boton_linaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_linaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_linajeActionPerformed(evt);
            }
        });
        jPanel8.add(boton_linaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 120, 100));

        boton_forg.setBackground(new java.awt.Color(235, 235, 235));
        boton_forg.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_forg.setText("Fecha de origen");
        boton_forg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_forg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_forgActionPerformed(evt);
            }
        });
        jPanel8.add(boton_forg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 30));

        boton_clasificacion.setBackground(new java.awt.Color(235, 235, 235));
        boton_clasificacion.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_clasificacion.setText("Clasificación");
        boton_clasificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_clasificacionActionPerformed(evt);
            }
        });
        jPanel8.add(boton_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 110, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 120, 100));

        JLabel_cedula.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        JLabel_cedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(JLabel_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 220, -1));

        jLabel4.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modificacion a la variante:");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        boton_sintomas.setBackground(new java.awt.Color(235, 235, 235));
        boton_sintomas.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_sintomas.setText("Síntomas");
        boton_sintomas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_sintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_sintomasActionPerformed(evt);
            }
        });
        jPanel8.add(boton_sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 110, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 770, 260));

        boton_volverAMain.setBackground(new java.awt.Color(235, 235, 235));
        boton_volverAMain.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_volverAMain.setText("Volver");
        boton_volverAMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_volverAMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_volverAMainActionPerformed(evt);
            }
        });
        jPanel7.add(boton_volverAMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 110, 30));

        Frame_modificar.getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel13.setBackground(new java.awt.Color(159, 211, 241));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDP1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDP1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDP1.setText("Guardar");
        boton_Siguiente_RegistroDP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDP1ActionPerformed(evt);
            }
        });
        jPanel13.add(boton_Siguiente_RegistroDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 80, 27));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(label_Fecha_Org3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, -1));

        label_Fecha_Nac3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac3.setText("Fecha de Origen: ");
        jPanel14.add(label_Fecha_Nac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 520, 90));

        title_persona.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona.setText("Nueva Fecha");
        jPanel13.add(title_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 520, 40));

        boton_Volver_RegistroDP2.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP2.setText("Volver");
        boton_Volver_RegistroDP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP2ActionPerformed(evt);
            }
        });
        jPanel13.add(boton_Volver_RegistroDP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, 27));

        jFrame_fechaorigen.getContentPane().add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(159, 211, 241));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDP2.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDP2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDP2.setText("Guardar");
        boton_Siguiente_RegistroDP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDP2ActionPerformed(evt);
            }
        });
        jPanel15.add(boton_Siguiente_RegistroDP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 27));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Fecha_Nac4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac4.setText("Clasificación: ");
        jPanel16.add(label_Fecha_Nac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        desplegable_clasificacion.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_clasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VOC", "VOI", "VUM" }));
        desplegable_clasificacion.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_clasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_clasificacionActionPerformed(evt);
            }
        });
        jPanel16.add(desplegable_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 190, 90));

        title_persona1.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona1.setText("Cambio de clasificación");
        jPanel15.add(title_persona1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 10, 520, 40));

        boton_Volver_RegistroDP3.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP3.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP3.setText("Volver");
        boton_Volver_RegistroDP3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP3ActionPerformed(evt);
            }
        });
        jPanel15.add(boton_Volver_RegistroDP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, 27));

        jFrame_clasificacion.getContentPane().add(jPanel15, java.awt.BorderLayout.CENTER);

        jPanel21.setBackground(new java.awt.Color(159, 211, 241));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Denominacion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion.setText("Síntomas:");
        jPanel22.add(label_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        desplegable_Sintomas.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Sintomas.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Sintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_SintomasActionPerformed(evt);
            }
        });
        jPanel22.add(desplegable_Sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, -1));

        TableSint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Síntomas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(TableSint);

        jPanel22.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, 110));

        boton_VerSintomas1.setBackground(new java.awt.Color(235, 235, 235));
        boton_VerSintomas1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_VerSintomas1.setText("Agregar");
        boton_VerSintomas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_VerSintomas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VerSintomas1ActionPerformed(evt);
            }
        });
        jPanel22.add(boton_VerSintomas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, 27));

        boton_VerSintomas.setBackground(new java.awt.Color(235, 235, 235));
        boton_VerSintomas.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_VerSintomas.setText("Eliminar");
        boton_VerSintomas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_VerSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VerSintomasActionPerformed(evt);
            }
        });
        jPanel22.add(boton_VerSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, 27));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 400, 230));

        title_persona4.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona4.setText("Cambio Síntomas");
        jPanel21.add(title_persona4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 10, 520, 40));

        boton_Volver_RegistroDP6.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP6.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP6.setText("Volver");
        boton_Volver_RegistroDP6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP6ActionPerformed(evt);
            }
        });
        jPanel21.add(boton_Volver_RegistroDP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 80, 27));

        jFrame_Sintomas.getContentPane().add(jPanel21, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver.setText("Volver");
        boton_Volver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VolverActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_VariantesRegistradas.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_VariantesRegistradas.setText("Variantes registradas: ");
        jPanel2.add(label_VariantesRegistradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        boton_ModificarVariante.setBackground(new java.awt.Color(235, 235, 235));
        boton_ModificarVariante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_ModificarVariante.setText("Modificar");
        boton_ModificarVariante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_ModificarVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ModificarVarianteActionPerformed(evt);
            }
        });
        jPanel2.add(boton_ModificarVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 90, 27));

        jTable_variantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Denominación ", "Linaje", "F. Org.", "Clasificación", "País"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_variantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_variantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_variantes);
        if (jTable_variantes.getColumnModel().getColumnCount() > 0) {
            jTable_variantes.getColumnModel().getColumn(0).setResizable(false);
            jTable_variantes.getColumnModel().getColumn(1).setResizable(false);
            jTable_variantes.getColumnModel().getColumn(2).setResizable(false);
            jTable_variantes.getColumnModel().getColumn(3).setResizable(false);
            jTable_variantes.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 920, 140));

        boton_BusVariante.setBackground(new java.awt.Color(235, 235, 235));
        boton_BusVariante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_BusVariante.setText("Buscar");
        boton_BusVariante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_BusVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_BusVarianteActionPerformed(evt);
            }
        });
        jPanel2.add(boton_BusVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 130, 100));

        boton_EliminarVariante.setBackground(new java.awt.Color(235, 235, 235));
        boton_EliminarVariante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_EliminarVariante.setText("Eliminar");
        boton_EliminarVariante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_EliminarVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EliminarVarianteActionPerformed(evt);
            }
        });
        jPanel2.add(boton_EliminarVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 90, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 130, 100));

        field_Denominacion.setBackground(new java.awt.Color(235, 235, 235));
        field_Denominacion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                field_DenominacionComponentAdded(evt);
            }
        });
        field_Denominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_DenominacionActionPerformed(evt);
            }
        });
        jPanel2.add(field_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 300, -1));

        boton_AggVariante.setBackground(new java.awt.Color(235, 235, 235));
        boton_AggVariante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_AggVariante.setText("Agregar");
        boton_AggVariante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_AggVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AggVarianteActionPerformed(evt);
            }
        });
        jPanel2.add(boton_AggVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 27));

        jTable_sintomas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Síntomas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_sintomas);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 270, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 940, 390));

        title_RegistroSintomas.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroSintomas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroSintomas.setText("Variantes");
        jPanel1.add(title_RegistroSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 890, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VolverActionPerformed
        // TODO add your handling code here:
         Proceso1 pro = new Proceso1();
        crea.InterfazDiferentes(this, pro, 697, 391);
    }//GEN-LAST:event_boton_VolverActionPerformed

    private void boton_ModificarVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ModificarVarianteActionPerformed
        if (jTable_variantes.getSelectedRow()!= -1){
            model = (DefaultTableModel) jTable_variantes.getModel();
            jLabel4.setText("Modificación a la variante con la denominación: "+model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString());//verificar jlabel
            
            crea.InterfazIguales(this, Frame_modificar, 880, 390);
        }else
            JOptionPane.showMessageDialog(null, "Debe seleccionar en la tabla la variante a modificar","Aviso",INFORMATION_MESSAGE);
    }//GEN-LAST:event_boton_ModificarVarianteActionPerformed

    private void boton_BusVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_BusVarianteActionPerformed
        Verificador veri = new Verificador();
        if (veri.dataNB(field_Denominacion)){
            //if (field_Denominacion.getText().toString().matches("-?\\d+")){
                //bus.limpiarTabla(jTable_recide);
                //bus.limpiarTabla(jTable_enfermedades);
                bus.limpiarTabla(jTable_sintomas);
                bus.limpiarTabla(jTable_variantes);
                bus.tableVariantes(jTable_variantes, field_Denominacion.getText());
            //}else
                //JOptionPane.showMessageDialog(null, "La denominación  debe ser texto","Error",ERROR_MESSAGE);
        }else{
           // bus.limpiarTabla(jTable_recide);
            //bus.limpiarTabla(jTable_enfermedades);
            bus.limpiarTabla(jTable_sintomas);
            bus.limpiarTabla(jTable_variantes);
            bus.tableAllvariantes(jTable_variantes);
        }
    }//GEN-LAST:event_boton_BusVarianteActionPerformed

    private void boton_EliminarVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EliminarVarianteActionPerformed
       model = (DefaultTableModel) jTable_variantes.getModel();
        bus.limpiarTabla(jTable_sintomas);
        if (jTable_variantes.getSelectedRow() != -1){
            bus.tableVarianteEli(model.getValueAt(jTable_variantes.getSelectedRow(),0).toString());
        
            bus.limpiarTabla(jTable_variantes);
            bus.tableAllvariantes(jTable_variantes);
        }else
            JOptionPane.showMessageDialog(null, "Debe seleccionar una persona para ser elimianda","Aviso",INFORMATION_MESSAGE); 
    }//GEN-LAST:event_boton_EliminarVarianteActionPerformed

    private void field_TiempoReposoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_TiempoReposoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_TiempoReposoActionPerformed

    private void field_DenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_DenominacionActionPerformed
        
    }//GEN-LAST:event_field_DenominacionActionPerformed

    private void field_DenominacionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_field_DenominacionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_field_DenominacionComponentAdded

    private void boton_AggVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AggVarianteActionPerformed
        // TODO add your handling code here:
        registrarVariante variante = new registrarVariante();
        crea.InterfazDiferentes(this, variante, 542, 425);
    }//GEN-LAST:event_boton_AggVarianteActionPerformed

    private void jTable_variantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_variantesMouseClicked
        model = (DefaultTableModel) jTable_variantes.getModel();
        String denom_oms = model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString();
        bus.limpiarTabla(jTable_sintomas);
        bus.tableVarSint(jTable_sintomas,denom_oms);
      /*  //bus.limpiarTabla(jTable_recide);
        bus.limpiarTabla(jTable_enfermedades);
        bus.tablePerEnf(jTable_enfermedades,CI);
        bus.tablePerRes(jTable_recide,CI);*/
    }//GEN-LAST:event_jTable_variantesMouseClicked

    private void boton_linajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_linajeActionPerformed
        String dato = JOptionPane.showInputDialog("Ingrese el nuevo linaje");
        if(dato != null){
            Verificador veri = new Verificador();
            if ((veri.dataNBS(dato))||(veri.noVacio(dato))){
                Guardar insertSQL = new Guardar();
                insertSQL.ModiVar(model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString(), dato, 1);
            }else{
                JOptionPane.showMessageDialog(null, "La información ingresada es incorrecta", "Error", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_boton_linajeActionPerformed

    private void boton_forgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_forgActionPerformed
        crea.InterfazIguales(Frame_modificar, jFrame_fechaorigen,590, 225);
    }//GEN-LAST:event_boton_forgActionPerformed

    private void boton_clasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_clasificacionActionPerformed
        // TODO add your handling code here:
        crea.InterfazIguales(Frame_modificar, jFrame_clasificacion, 258,225);
    }//GEN-LAST:event_boton_clasificacionActionPerformed

    private void boton_sintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_sintomasActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listas = dataSQL.descripsintoma(dataSQL.Sintomas());
        desplegable_Sintomas.removeAllItems();
        for (int i=0;i<listas.size();i++)
            desplegable_Sintomas.addItem(listas.get(i));
        bus.tableVarSint(TableSint, model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString());
        crea.InterfazIguales(Frame_modificar, jFrame_Sintomas, 480, 360); //462, 344
    }//GEN-LAST:event_boton_sintomasActionPerformed

    private void boton_volverAMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_volverAMainActionPerformed
        crea.InterfazIguales(Frame_modificar, this, 1008, 550);
        bus.limpiarTabla(jTable_variantes);
        bus.tableAllvariantes(jTable_variantes);
    }//GEN-LAST:event_boton_volverAMainActionPerformed

    private void boton_Siguiente_RegistroDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDP1ActionPerformed
        Date date = label_Fecha_Org3.getDate();
        long da = date.getTime();
        java.sql.Date fecha = new java.sql.Date(da);
        Guardar insertSQL = new Guardar();
        insertSQL.ModiVar(model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString(), fecha.toString(),2);
    }//GEN-LAST:event_boton_Siguiente_RegistroDP1ActionPerformed

    private void boton_Volver_RegistroDP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP2ActionPerformed
        crea.InterfazIguales(jFrame_fechaorigen, Frame_modificar, 880, 390);
        bus.limpiarTabla(jTable_variantes);
        bus.tableAllvariantes(jTable_variantes);
    }//GEN-LAST:event_boton_Volver_RegistroDP2ActionPerformed

    private void boton_Siguiente_RegistroDP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDP2ActionPerformed
        Guardar insertSQL = new Guardar();
        insertSQL.ModiVar(model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString(), desplegable_clasificacion.getSelectedItem().toString(),3);
    }//GEN-LAST:event_boton_Siguiente_RegistroDP2ActionPerformed

    private void boton_Volver_RegistroDP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP3ActionPerformed
        crea.InterfazIguales(jFrame_clasificacion, Frame_modificar, 880, 390);
    }//GEN-LAST:event_boton_Volver_RegistroDP3ActionPerformed

    private void desplegable_clasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_clasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_clasificacionActionPerformed

    private void desplegable_SintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_SintomasActionPerformed
        
    }//GEN-LAST:event_desplegable_SintomasActionPerformed

    private void boton_VerSintomas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VerSintomas1ActionPerformed
        Verificador veri = new Verificador();
        DefaultTableModel modelSint = (DefaultTableModel) TableSint.getModel();
        String dato;
        dato = desplegable_Sintomas.getSelectedItem().toString();
        if(!veri.existenciaTable(model, dato)){
            modelSint.addRow(new Object[]{dato});
            Guardar insertSQL = new Guardar();
            insertSQL.guardarSintVar(dato, model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString());
        }
    }//GEN-LAST:event_boton_VerSintomas1ActionPerformed

    private void boton_VerSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VerSintomasActionPerformed
        DefaultTableModel modelSint = (DefaultTableModel) TableSint.getModel();
        if (TableSint.getSelectedRow() != -1){
            bus.tableVarSintEliIte(model.getValueAt(jTable_variantes.getSelectedRow(), 0).toString(), TableSint);
            modelSint.removeRow(TableSint.getSelectedRow());
        }
        else
        JOptionPane.showMessageDialog(null, "No ha seleccionado una enfermedad a eliminar","Warning",WARNING_MESSAGE);
    }//GEN-LAST:event_boton_VerSintomasActionPerformed

    private void boton_Volver_RegistroDP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP6ActionPerformed
        crea.InterfazIguales(jFrame_Sintomas, Frame_modificar, 880, 390);
        bus.limpiarTabla(TableSint);
    }//GEN-LAST:event_boton_Volver_RegistroDP6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionVariante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionVariante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionVariante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVisualizacionVariante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVisualizacionVariante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Frame_modificar;
    private javax.swing.JLabel JLabel_cedula;
    private javax.swing.JTable TableSint;
    private javax.swing.JButton boton_AggVariante;
    private javax.swing.JButton boton_BusVariante;
    private javax.swing.JButton boton_EliminarVariante;
    private javax.swing.JButton boton_ModificarVariante;
    private javax.swing.JButton boton_Siguiente_RegistroDP1;
    private javax.swing.JButton boton_Siguiente_RegistroDP2;
    private javax.swing.JButton boton_VerSintomas;
    private javax.swing.JButton boton_VerSintomas1;
    private javax.swing.JButton boton_Volver;
    private javax.swing.JButton boton_Volver_RegistroDP2;
    private javax.swing.JButton boton_Volver_RegistroDP3;
    private javax.swing.JButton boton_Volver_RegistroDP6;
    private javax.swing.JButton boton_clasificacion;
    private javax.swing.JButton boton_forg;
    private javax.swing.JButton boton_linaje;
    private javax.swing.JButton boton_sintomas;
    private javax.swing.JButton boton_volverAMain;
    private javax.swing.JComboBox<String> desplegable_Sintomas;
    private javax.swing.JComboBox<String> desplegable_clasificacion;
    private javax.swing.JTextField field_Denominacion;
    private javax.swing.JTextField field_TiempoReposo;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame_Sintomas;
    private javax.swing.JFrame jFrame_clasificacion;
    private javax.swing.JFrame jFrame_fechaorigen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_sintomas;
    private javax.swing.JTable jTable_variantes;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel label_Denominacion;
    private javax.swing.JLabel label_Fecha_Nac3;
    private javax.swing.JLabel label_Fecha_Nac4;
    private com.toedter.calendar.JDateChooser label_Fecha_Org3;
    private javax.swing.JLabel label_VariantesRegistradas;
    private javax.swing.JLabel title_RegistroSintomas;
    private javax.swing.JLabel title_persona;
    private javax.swing.JLabel title_persona1;
    private javax.swing.JLabel title_persona4;
    // End of variables declaration//GEN-END:variables
}
