/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Buscador;
import Clases.Estado;
import SQL.Extraer;
import SQL.Guardar;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import tools.Creador;
import tools.Verificador;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarPersona extends javax.swing.JFrame {
    Extraer dataSQL = new Extraer();
    DefaultTableModel model;
    Creador crea = new Creador();
    
    public registrarPersona() {
        initComponents();
        Creador crea = new Creador();
        crea.addTableHeaderEnfer(model,TableEnfer);
        crea.Interfaz(this, 594, 580);
        ArrayList<String> listas = dataSQL.nombPais(dataSQL.Pais());
        for (int i=0;i<listas.size();i++)
        desplegable_Pais1.addItem(listas.get(i));
        listas = dataSQL.nombEnfermedad(dataSQL.Enfermedad());
        for (int i=0;i<listas.size();i++)
        desplegable_Enfermedad.addItem(listas.get(i));
        jDateChooser1.getDateEditor().setEnabled(false);
        jDateChooser1.getJCalendar().setMaxSelectableDate(new Date());
        jDateChooser1.setDate(new Date(System.currentTimeMillis()));
        jDateChooser2.getDateEditor().setEnabled(false);
        jDateChooser2.getJCalendar().setMaxSelectableDate(new Date());
        jDateChooser2.setDate(new Date(System.currentTimeMillis()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        regisEnfermedad = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        boton_Volver_Variante = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label_Denominacion = new javax.swing.JLabel();
        desplegable_Enfermedad = new javax.swing.JComboBox<String>();
        boton_VerSintomas = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableEnfer = new javax.swing.JTable();
        boton_VerSintomas1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        boton_AggEnferNueva = new javax.swing.JButton();
        title_RegistroVariante = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDP1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        desplegable_Pais1 = new javax.swing.JComboBox<String>();
        desplegable_Sexo = new javax.swing.JComboBox<String>();
        desplegable_AltoRiesgo = new javax.swing.JComboBox<String>();
        desplegable_Nacionalidad = new javax.swing.JComboBox<String>();
        desplegable_Estado1 = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        label_Pais = new javax.swing.JLabel();
        label_nombre_Per = new javax.swing.JLabel();
        label_Apellido_Per = new javax.swing.JLabel();
        label_Numero_Doc = new javax.swing.JLabel();
        label_Fecha_Nac = new javax.swing.JLabel();
        label_Ntelefono = new javax.swing.JLabel();
        label_AltoRiesgo = new javax.swing.JLabel();
        label_Estado = new javax.swing.JLabel();
        label_Enfermedad = new javax.swing.JLabel();
        label_Sexo = new javax.swing.JLabel();
        label_Ocupacion3 = new javax.swing.JLabel();
        label_Direccion = new javax.swing.JLabel();
        boton_Enfermedad = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        label_Fecha_Nac1 = new javax.swing.JLabel();
        field_Apellido_Persona = new javax.swing.JTextField();
        field_Nombre_Persona = new javax.swing.JTextField();
        field_Numero_Doc1 = new javax.swing.JTextField();
        field_Ocupacion = new javax.swing.JTextField();
        field_NTelefono = new javax.swing.JTextField();
        field_Direccion = new javax.swing.JTextField();
        title_persona = new javax.swing.JLabel();
        boton_Volver_RegistroDP2 = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(159, 211, 241));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver_Variante.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_Variante.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_Variante.setText("Volver");
        boton_Volver_Variante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_Variante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_VarianteActionPerformed(evt);
            }
        });
        jPanel3.add(boton_Volver_Variante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 80, 27));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Denominacion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Denominacion.setText("Enfermedades:");
        jPanel4.add(label_Denominacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        desplegable_Enfermedad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Enfermedad.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Enfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_EnfermedadActionPerformed(evt);
            }
        });
        jPanel4.add(desplegable_Enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 240, -1));

        boton_VerSintomas.setBackground(new java.awt.Color(235, 235, 235));
        boton_VerSintomas.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_VerSintomas.setText("Eliminar");
        boton_VerSintomas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_VerSintomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VerSintomasActionPerformed(evt);
            }
        });
        jPanel4.add(boton_VerSintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 90, 27));

        TableEnfer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enfermedades"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableEnfer);
        if (TableEnfer.getColumnModel().getColumnCount() > 0) {
            TableEnfer.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, 110));

        boton_VerSintomas1.setBackground(new java.awt.Color(235, 235, 235));
        boton_VerSintomas1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_VerSintomas1.setText("Agregar");
        boton_VerSintomas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_VerSintomas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VerSintomas1ActionPerformed(evt);
            }
        });
        jPanel4.add(boton_VerSintomas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, 27));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 100, 110));

        boton_AggEnferNueva.setBackground(new java.awt.Color(235, 235, 235));
        boton_AggEnferNueva.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_AggEnferNueva.setText("Agregar nueva");
        boton_AggEnferNueva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_AggEnferNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AggEnferNuevaActionPerformed(evt);
            }
        });
        jPanel4.add(boton_AggEnferNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, 27));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 410, 250));

        title_RegistroVariante.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_RegistroVariante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_RegistroVariante.setText("Registro de enfermedades");
        jPanel3.add(title_RegistroVariante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, 40));

        regisEnfermedad.getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("rgistroPersona");

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDP1.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDP1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDP1.setText("Siguiente");
        boton_Siguiente_RegistroDP1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDP1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 500, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        desplegable_Pais1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Pais1.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Pais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_Pais1ActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Pais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, -1));

        desplegable_Sexo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Sexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F", "M", "N/A" }));
        desplegable_Sexo.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, -1));

        desplegable_AltoRiesgo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_AltoRiesgo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        desplegable_AltoRiesgo.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_AltoRiesgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_AltoRiesgoActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_AltoRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 160, -1));

        desplegable_Nacionalidad.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Nacionalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "V", "E" }));
        desplegable_Nacionalidad.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Nacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 50, -1));

        desplegable_Estado1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Estado1.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Estado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 154, 110));

        label_Pais.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Pais.setText("País: ");
        jPanel2.add(label_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label_nombre_Per.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_nombre_Per.setText("Nombre:");
        jPanel2.add(label_nombre_Per, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        label_Apellido_Per.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Apellido_Per.setText("Apellido:");
        jPanel2.add(label_Apellido_Per, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        label_Numero_Doc.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Numero_Doc.setText("Número de documento:");
        jPanel2.add(label_Numero_Doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_Fecha_Nac.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac.setText("Fecha de residencia: ");
        jPanel2.add(label_Fecha_Nac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label_Ntelefono.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Ntelefono.setText("Número de teléfono:");
        jPanel2.add(label_Ntelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        label_AltoRiesgo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_AltoRiesgo.setText("Alto Riesgos:");
        jPanel2.add(label_AltoRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        label_Estado.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Estado.setText("Estado: ");
        jPanel2.add(label_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        label_Enfermedad.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Enfermedad.setText("Enfermedades:");
        jPanel2.add(label_Enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        label_Sexo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Sexo.setText("Sexo: ");
        jPanel2.add(label_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        label_Ocupacion3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Ocupacion3.setText("Ocupación:");
        jPanel2.add(label_Ocupacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        label_Direccion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Direccion.setText("Dirección:");
        jPanel2.add(label_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        boton_Enfermedad.setBackground(new java.awt.Color(235, 235, 235));
        boton_Enfermedad.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Enfermedad.setText("Agregar enfermedad");
        boton_Enfermedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Enfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_EnfermedadActionPerformed(evt);
            }
        });
        jPanel2.add(boton_Enfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 140, 27));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, -1));
        jPanel2.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        label_Fecha_Nac1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Nac1.setText("Fecha de Nacimiento: ");
        jPanel2.add(label_Fecha_Nac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        field_Apellido_Persona.setBackground(new java.awt.Color(235, 235, 235));
        field_Apellido_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Apellido_PersonaActionPerformed(evt);
            }
        });
        jPanel2.add(field_Apellido_Persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 140, -1));

        field_Nombre_Persona.setBackground(new java.awt.Color(235, 235, 235));
        field_Nombre_Persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Nombre_PersonaActionPerformed(evt);
            }
        });
        field_Nombre_Persona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                field_Nombre_PersonaKeyTyped(evt);
            }
        });
        jPanel2.add(field_Nombre_Persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, -1));

        field_Numero_Doc1.setBackground(new java.awt.Color(235, 235, 235));
        field_Numero_Doc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_Numero_Doc1ActionPerformed(evt);
            }
        });
        jPanel2.add(field_Numero_Doc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 200, -1));

        field_Ocupacion.setBackground(new java.awt.Color(235, 235, 235));
        field_Ocupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_OcupacionActionPerformed(evt);
            }
        });
        jPanel2.add(field_Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 220, -1));

        field_NTelefono.setBackground(new java.awt.Color(235, 235, 235));
        field_NTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_NTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(field_NTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 200, -1));

        field_Direccion.setBackground(new java.awt.Color(235, 235, 235));
        field_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_DireccionActionPerformed(evt);
            }
        });
        jPanel2.add(field_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 520, 430));

        title_persona.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona.setText("Registro de datos personales");
        jPanel1.add(title_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 520, 40));

        boton_Volver_RegistroDP2.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDP2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDP2.setText("Volver");
        boton_Volver_RegistroDP2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDP2ActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroDP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 80, 27));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_EnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_EnfermedadActionPerformed
        crea.InterfazIguales(this, regisEnfermedad, 467, 385);    
    }//GEN-LAST:event_boton_EnfermedadActionPerformed

    private void boton_Siguiente_RegistroDP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDP1ActionPerformed
        Verificador veri = new Verificador();
        if((veri.dataNB(field_Nombre_Persona))&&(veri.dataNB(field_Apellido_Persona))&&(veri.dataNB(field_Numero_Doc1))&&(veri.dataNB(field_Ocupacion))&&(veri.dataNB(field_NTelefono))&&(veri.dataNB(field_Direccion))){
            if((veri.noVacio(field_Nombre_Persona.getText().toString()))&&(veri.noVacio(field_Apellido_Persona.getText().toString()))&&(veri.noVacio(field_Numero_Doc1.getText().toString()))&&(veri.noVacio(field_Ocupacion.getText().toString()))&&(veri.noVacio(field_NTelefono.getText().toString()))&&(veri.noVacio(field_Direccion.getText().toString()))){
                if((field_NTelefono.getText().toString().matches("-?\\d+"))&&(field_Numero_Doc1.getText().toString().matches("-?\\d+"))){
                    Guardar insertSQL = new Guardar();
                    if (insertSQL.guardadoPersona(desplegable_Nacionalidad.getSelectedItem().toString()+field_Numero_Doc1.getText().toString(),field_Nombre_Persona, field_Apellido_Persona, jDateChooser1, desplegable_Sexo.getSelectedItem().toString(), field_Direccion, field_NTelefono,veri.altoRiesgo(desplegable_AltoRiesgo.getSelectedItem().toString()), field_Ocupacion.getText().toString(), desplegable_Estado1.getSelectedItem().toString(), desplegable_Pais1.getSelectedItem().toString(),jDateChooser2))
                        insertSQL.iteGuardarEnfePer(TableEnfer, desplegable_Nacionalidad.getSelectedItem().toString()+field_Numero_Doc1.getText().toString());
                }else
                    JOptionPane.showMessageDialog(null,"La informacion en los campos numericos no es valida","Error",ERROR_MESSAGE);    
            }else{
                JOptionPane.showMessageDialog(null, "No se admiten casillas con unicamente espacios en blanco","Error",ERROR_MESSAGE);
            }
        }else
            JOptionPane.showMessageDialog(null, "Se encuentran casillas sin rellenar","Error",ERROR_MESSAGE);
    }//GEN-LAST:event_boton_Siguiente_RegistroDP1ActionPerformed

    private void desplegable_AltoRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_AltoRiesgoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_AltoRiesgoActionPerformed

    private void desplegable_Pais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_Pais1ActionPerformed
        desplegable_Estado1.removeAllItems();
        String codpais = desplegable_Pais1.getSelectedItem().toString();
        Buscador busc = new Buscador();
        ArrayList<String> listas = dataSQL.nombEstado(dataSQL.Estado(busc.codPais(codpais)));
        for (int i=0;i<listas.size();i++)
        desplegable_Estado1.addItem(listas.get(i));
    }//GEN-LAST:event_desplegable_Pais1ActionPerformed

    private void boton_Volver_RegistroDP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDP2ActionPerformed

    }//GEN-LAST:event_boton_Volver_RegistroDP2ActionPerformed

    private void boton_Volver_VarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_VarianteActionPerformed
        crea.InterfazIguales(regisEnfermedad, this, 594, 580); 
    }//GEN-LAST:event_boton_Volver_VarianteActionPerformed

    private void desplegable_EnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_EnfermedadActionPerformed
        
    }//GEN-LAST:event_desplegable_EnfermedadActionPerformed

    private void boton_VerSintomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VerSintomasActionPerformed
        model = (DefaultTableModel) TableEnfer.getModel();
        System.out.println(TableEnfer.getSelectedRow());
        if (TableEnfer.getSelectedRow() != -1)
            model.removeRow(TableEnfer.getSelectedRow());
        else
            JOptionPane.showMessageDialog(null, "No ha seleccionado una enfermedad a eliminar","Warning",WARNING_MESSAGE);
    }//GEN-LAST:event_boton_VerSintomasActionPerformed

    private void boton_VerSintomas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VerSintomas1ActionPerformed
        Verificador veri = new Verificador();
        model = (DefaultTableModel) TableEnfer.getModel();
        String dato;
        dato = desplegable_Enfermedad.getSelectedItem().toString();
        if(!veri.existenciaTable(model, dato)){
            model.addRow(new Object[]{dato});
        }
    }//GEN-LAST:event_boton_VerSintomas1ActionPerformed

    private void field_Nombre_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Nombre_PersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Nombre_PersonaActionPerformed

    private void field_Apellido_PersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Apellido_PersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Apellido_PersonaActionPerformed

    private void field_Numero_Doc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_Numero_Doc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_Numero_Doc1ActionPerformed

    private void field_OcupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_OcupacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_OcupacionActionPerformed

    private void field_NTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_NTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_NTelefonoActionPerformed

    private void field_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_DireccionActionPerformed

    private void boton_AggEnferNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AggEnferNuevaActionPerformed
        String nuevaEnfermedad = JOptionPane.showInputDialog("Ingrese enfermedad");
        if(nuevaEnfermedad != null){
            Verificador veri = new Verificador();
            if (veri.dataNBS(nuevaEnfermedad)){
                Guardar insertSQL = new Guardar();
                if(insertSQL.guardarEnfermedad(nuevaEnfermedad)){
                    ArrayList<String> listas = dataSQL.nombEnfermedad(dataSQL.Enfermedad());
                    desplegable_Enfermedad.removeAllItems();
                    for (int i = 0; i < listas.size(); i++) {
                        desplegable_Enfermedad.addItem(listas.get(i));
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null, "La información ingresada es incorrecta", "Error", ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_boton_AggEnferNuevaActionPerformed

    private void field_Nombre_PersonaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_field_Nombre_PersonaKeyTyped
       
    }//GEN-LAST:event_field_Nombre_PersonaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableEnfer;
    private javax.swing.JButton boton_AggEnferNueva;
    private javax.swing.JButton boton_Enfermedad;
    private javax.swing.JButton boton_Siguiente_RegistroDP1;
    private javax.swing.JButton boton_VerSintomas;
    private javax.swing.JButton boton_VerSintomas1;
    private javax.swing.JButton boton_Volver_RegistroDP2;
    private javax.swing.JButton boton_Volver_Variante;
    private javax.swing.JComboBox<String> desplegable_AltoRiesgo;
    private javax.swing.JComboBox<String> desplegable_Enfermedad;
    private javax.swing.JComboBox<String> desplegable_Estado1;
    private javax.swing.JComboBox<String> desplegable_Nacionalidad;
    private javax.swing.JComboBox<String> desplegable_Pais1;
    private javax.swing.JComboBox<String> desplegable_Sexo;
    private javax.swing.JTextField field_Apellido_Persona;
    private javax.swing.JTextField field_Direccion;
    private javax.swing.JTextField field_NTelefono;
    private javax.swing.JTextField field_Nombre_Persona;
    private javax.swing.JTextField field_Numero_Doc1;
    private javax.swing.JTextField field_Ocupacion;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_AltoRiesgo;
    private javax.swing.JLabel label_Apellido_Per;
    private javax.swing.JLabel label_Denominacion;
    private javax.swing.JLabel label_Direccion;
    private javax.swing.JLabel label_Enfermedad;
    private javax.swing.JLabel label_Estado;
    private javax.swing.JLabel label_Fecha_Nac;
    private javax.swing.JLabel label_Fecha_Nac1;
    private javax.swing.JLabel label_Ntelefono;
    private javax.swing.JLabel label_Numero_Doc;
    private javax.swing.JLabel label_Ocupacion3;
    private javax.swing.JLabel label_Pais;
    private javax.swing.JLabel label_Sexo;
    private javax.swing.JLabel label_nombre_Per;
    private javax.swing.JFrame regisEnfermedad;
    private javax.swing.JLabel title_RegistroVariante;
    private javax.swing.JLabel title_persona;
    // End of variables declaration//GEN-END:variables
}
