/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarCentroSalud extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarCentroSalud() {
        initComponents();
        this.setSize(543,460);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Siguiente_Centro = new javax.swing.JButton();
        boton_Volver_RegistroCentro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Pais = new javax.swing.JLabel();
        label_nombreCentro = new javax.swing.JLabel();
        field_nombreCentro = new java.awt.TextField();
        label_direccionCentro = new javax.swing.JLabel();
        label_TipoCentro = new javax.swing.JLabel();
        field_direccionCentro = new java.awt.TextField();
        label_MedicoE = new javax.swing.JLabel();
        label_Estado = new javax.swing.JLabel();
        desplegable_Estado = new javax.swing.JComboBox<>();
        desplegable_Pais = new javax.swing.JComboBox<>();
        desplegable_TipoCentro = new javax.swing.JComboBox<>();
        desplegable_MedicoE = new javax.swing.JComboBox<>();
        label_Fecha_Origen = new javax.swing.JLabel();
        desplegable_calendar = new com.toedter.calendar.JDateChooser();
        title_CentroSalud = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_Centro.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_Centro.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_Centro.setText("Aceptar");
        boton_Siguiente_Centro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_CentroActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 80, 27));

        boton_Volver_RegistroCentro.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroCentro.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroCentro.setText("Volver");
        boton_Volver_RegistroCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroCentroActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 154, 110));

        label_Pais.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Pais.setText("País: ");
        jPanel2.add(label_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        label_nombreCentro.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_nombreCentro.setText("Nombre:");
        jPanel2.add(label_nombreCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        field_nombreCentro.setBackground(new java.awt.Color(235, 235, 235));
        field_nombreCentro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_nombreCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 180, -1));

        label_direccionCentro.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_direccionCentro.setText("Dirección:");
        jPanel2.add(label_direccionCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_TipoCentro.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_TipoCentro.setText("Tipo de centro:");
        jPanel2.add(label_TipoCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        field_direccionCentro.setBackground(new java.awt.Color(235, 235, 235));
        field_direccionCentro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(field_direccionCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 310, -1));

        label_MedicoE.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_MedicoE.setText("Médico encargado: ");
        jPanel2.add(label_MedicoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label_Estado.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Estado.setText("Estado: ");
        jPanel2.add(label_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        desplegable_Estado.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Estado.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, -1));

        desplegable_Pais.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Pais.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_PaisActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 180, -1));

        desplegable_TipoCentro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_TipoCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vacunación", "Hospitalización" }));
        desplegable_TipoCentro.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_TipoCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 180, -1));

        desplegable_MedicoE.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_MedicoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_MedicoE.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_MedicoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, -1));

        label_Fecha_Origen.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Origen.setText("Fecha de Encargo: ");
        jPanel2.add(label_Fecha_Origen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        desplegable_calendar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(desplegable_calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 180, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 310));

        title_CentroSalud.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_CentroSalud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_CentroSalud.setText("Registro centro de salud");
        jPanel1.add(title_CentroSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroCentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroCentroActionPerformed

    private void boton_Siguiente_CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_CentroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_CentroActionPerformed

    private void desplegable_PaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_PaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_PaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarCentroSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarCentroSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarCentroSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarCentroSalud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarCentroSalud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Siguiente_Centro;
    private javax.swing.JButton boton_Volver_RegistroCentro;
    private javax.swing.JComboBox<String> desplegable_Estado;
    private javax.swing.JComboBox<String> desplegable_MedicoE;
    private javax.swing.JComboBox<String> desplegable_Pais;
    private javax.swing.JComboBox<String> desplegable_TipoCentro;
    private com.toedter.calendar.JDateChooser desplegable_calendar;
    private java.awt.TextField field_direccionCentro;
    private java.awt.TextField field_nombreCentro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Estado;
    private javax.swing.JLabel label_Fecha_Origen;
    private javax.swing.JLabel label_MedicoE;
    private javax.swing.JLabel label_Pais;
    private javax.swing.JLabel label_TipoCentro;
    private javax.swing.JLabel label_direccionCentro;
    private javax.swing.JLabel label_nombreCentro;
    private javax.swing.JLabel title_CentroSalud;
    // End of variables declaration//GEN-END:variables
}
