/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarPersonaVacunada extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarPersonaVacunada() {
        initComponents();
        this.setSize(545,369);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Siguiente_RegistroDPV = new javax.swing.JButton();
        boton_Volver_RegistroDPV = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_CentroSalud = new javax.swing.JLabel();
        label_nombre_VacApli = new javax.swing.JLabel();
        field_Numero_Dosis = new java.awt.TextField();
        label_Numero_Dosis = new javax.swing.JLabel();
        label_Fecha_Vacunacion = new javax.swing.JLabel();
        label_PersonalSalud = new javax.swing.JLabel();
        desplegable_calendar = new com.toedter.calendar.JDateChooser();
        desplegable_PersonalSalud = new javax.swing.JComboBox<>();
        desplegable_VacApli = new javax.swing.JComboBox<>();
        desplegable_CentroApli = new javax.swing.JComboBox<>();
        title_persona = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroDPV.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroDPV.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroDPV.setText("Siguiente");
        boton_Siguiente_RegistroDPV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroDPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroDPVActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroDPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 80, 27));

        boton_Volver_RegistroDPV.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroDPV.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroDPV.setText("Volver");
        boton_Volver_RegistroDPV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroDPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroDPVActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroDPV, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 154, 110));

        label_CentroSalud.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        label_CentroSalud.setText("Centro de salud:");
        jPanel2.add(label_CentroSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label_nombre_VacApli.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        label_nombre_VacApli.setText("Nombre de la vacuna aplicada:");
        jPanel2.add(label_nombre_VacApli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        field_Numero_Dosis.setBackground(new java.awt.Color(235, 235, 235));
        field_Numero_Dosis.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jPanel2.add(field_Numero_Dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, -1));

        label_Numero_Dosis.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        label_Numero_Dosis.setText("N° de dosis: ");
        jPanel2.add(label_Numero_Dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        label_Fecha_Vacunacion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        label_Fecha_Vacunacion.setText("Fecha de vacunación: ");
        jPanel2.add(label_Fecha_Vacunacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_PersonalSalud.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        label_PersonalSalud.setText("Personal de salud:");
        jPanel2.add(label_PersonalSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        desplegable_calendar.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(desplegable_calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, 20));

        desplegable_PersonalSalud.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_PersonalSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_PersonalSalud.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_PersonalSalud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_PersonalSaludActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_PersonalSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 180, -1));

        desplegable_VacApli.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_VacApli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_VacApli.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_VacApli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 180, -1));

        desplegable_CentroApli.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_CentroApli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_CentroApli.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_CentroApli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 220));

        title_persona.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_persona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_persona.setText("Registro de datos personales");
        jPanel1.add(title_persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroDPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroDPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroDPVActionPerformed

    private void boton_Siguiente_RegistroDPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroDPVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_RegistroDPVActionPerformed

    private void desplegable_PersonalSaludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_PersonalSaludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_PersonalSaludActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarPersonaVacunada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarPersonaVacunada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarPersonaVacunada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarPersonaVacunada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarPersonaVacunada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Siguiente_RegistroDPV;
    private javax.swing.JButton boton_Volver_RegistroDPV;
    private javax.swing.JComboBox<String> desplegable_CentroApli;
    private javax.swing.JComboBox<String> desplegable_PersonalSalud;
    private javax.swing.JComboBox<String> desplegable_VacApli;
    private com.toedter.calendar.JDateChooser desplegable_calendar;
    private java.awt.TextField field_Numero_Dosis;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_CentroSalud;
    private javax.swing.JLabel label_Fecha_Vacunacion;
    private javax.swing.JLabel label_Numero_Dosis;
    private javax.swing.JLabel label_PersonalSalud;
    private javax.swing.JLabel label_nombre_VacApli;
    private javax.swing.JLabel title_persona;
    // End of variables declaration//GEN-END:variables
}
