/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarTratamiento extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarTratamiento() {
        initComponents();
        this.setSize(545, 499);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Volver_RegistroT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        label_imagen = new javax.swing.JLabel();
        label_Medicamentos = new javax.swing.JLabel();
        label_Fecha_Contagio = new javax.swing.JLabel();
        label_Dosis = new javax.swing.JLabel();
        desplegable_Medicamentos = new javax.swing.JComboBox<String>();
        boton_AnadirMed = new javax.swing.JButton();
        label_Frecuencia = new javax.swing.JLabel();
        label_CantDias = new javax.swing.JLabel();
        boton_VerMed = new javax.swing.JButton();
        field_CantDias = new javax.swing.JTextField();
        field_Frecuencia = new javax.swing.JTextField();
        field_Dosis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        field_Nombre_Persona1 = new javax.swing.JTextArea();
        title_Tratamiento = new javax.swing.JLabel();
        boton_Siguiente_RegistroT = new javax.swing.JButton();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Volver_RegistroT.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroT.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroT.setText("Volver");
        boton_Volver_RegistroT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroTActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(label_imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 154, 110));

        label_Medicamentos.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Medicamentos.setText("Medicamentos:");
        jPanel2.add(label_Medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        label_Fecha_Contagio.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Contagio.setText("Descripción del tratamiento: ");
        jPanel2.add(label_Fecha_Contagio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        label_Dosis.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Dosis.setText("Dosis:");
        jPanel2.add(label_Dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        desplegable_Medicamentos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Medicamentos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Medicamentos.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Medicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_MedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Medicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        boton_AnadirMed.setBackground(new java.awt.Color(235, 235, 235));
        boton_AnadirMed.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_AnadirMed.setText("Añadir");
        boton_AnadirMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_AnadirMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_AnadirMedActionPerformed(evt);
            }
        });
        jPanel2.add(boton_AnadirMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, 27));

        label_Frecuencia.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Frecuencia.setText("Frecuencia:");
        jPanel2.add(label_Frecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        label_CantDias.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_CantDias.setText("Cantidad de días:");
        jPanel2.add(label_CantDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        boton_VerMed.setBackground(new java.awt.Color(235, 235, 235));
        boton_VerMed.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_VerMed.setText("Ver medicamentos");
        boton_VerMed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_VerMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_VerMedActionPerformed(evt);
            }
        });
        jPanel2.add(boton_VerMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, 27));

        field_CantDias.setBackground(new java.awt.Color(235, 235, 235));
        field_CantDias.setForeground(new java.awt.Color(0, 0, 0));
        field_CantDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_CantDiasActionPerformed(evt);
            }
        });
        jPanel2.add(field_CantDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 190, -1));

        field_Frecuencia.setBackground(new java.awt.Color(235, 235, 235));
        field_Frecuencia.setForeground(new java.awt.Color(0, 0, 0));
        field_Frecuencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_FrecuenciaActionPerformed(evt);
            }
        });
        jPanel2.add(field_Frecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 190, -1));

        field_Dosis.setBackground(new java.awt.Color(235, 235, 235));
        field_Dosis.setForeground(new java.awt.Color(0, 0, 0));
        field_Dosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_DosisActionPerformed(evt);
            }
        });
        jPanel2.add(field_Dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 190, -1));

        field_Nombre_Persona1.setBackground(new java.awt.Color(235, 235, 235));
        field_Nombre_Persona1.setColumns(17);
        field_Nombre_Persona1.setForeground(new java.awt.Color(0, 0, 0));
        field_Nombre_Persona1.setRows(5);
        jScrollPane1.setViewportView(field_Nombre_Persona1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 350));

        title_Tratamiento.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_Tratamiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Tratamiento.setText("Registro de Tratamiento");
        jPanel1.add(title_Tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        boton_Siguiente_RegistroT.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroT.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroT.setText("Aceptar");
        boton_Siguiente_RegistroT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroTActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 80, 27));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroTActionPerformed

    private void boton_AnadirMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_AnadirMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_AnadirMedActionPerformed

    private void desplegable_MedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_MedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_MedicamentosActionPerformed

    private void boton_VerMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_VerMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_VerMedActionPerformed

    private void boton_Siguiente_RegistroTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_RegistroTActionPerformed

    private void field_CantDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_CantDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_CantDiasActionPerformed

    private void field_FrecuenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_FrecuenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_FrecuenciaActionPerformed

    private void field_DosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_DosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_DosisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarTratamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarTratamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_AnadirMed;
    private javax.swing.JButton boton_Siguiente_RegistroT;
    private javax.swing.JButton boton_VerMed;
    private javax.swing.JButton boton_Volver_RegistroT;
    private javax.swing.JComboBox<String> desplegable_Medicamentos;
    private javax.swing.JTextField field_CantDias;
    private javax.swing.JTextField field_Dosis;
    private javax.swing.JTextField field_Frecuencia;
    private javax.swing.JTextArea field_Nombre_Persona1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_CantDias;
    private javax.swing.JLabel label_Dosis;
    private javax.swing.JLabel label_Fecha_Contagio;
    private javax.swing.JLabel label_Frecuencia;
    private javax.swing.JLabel label_Medicamentos;
    private javax.swing.JLabel label_imagen;
    private javax.swing.JLabel title_Tratamiento;
    // End of variables declaration//GEN-END:variables
}
