/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Ricardo Fanghella
 */
public class registrarTratamientoPaciente extends javax.swing.JFrame {

    /**
     * Creates new form registrarMedicamento
     */
    public registrarTratamientoPaciente() {
        initComponents();
        this.setSize(542, 449);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton_Siguiente_RegistroPT = new javax.swing.JButton();
        boton_Volver_RegistroPT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_Fecha_Trata = new javax.swing.JLabel();
        label_Numero_TratamientoPaciente = new javax.swing.JLabel();
        label_Tratamiento = new javax.swing.JLabel();
        label_Centro = new javax.swing.JLabel();
        label_EstadoReposo = new javax.swing.JLabel();
        desplegable_calendarTrata = new com.toedter.calendar.JDateChooser();
        desplegable_EstadoReposo = new javax.swing.JComboBox<>();
        desplegable_NacionalidadTratamientoPaciente = new javax.swing.JComboBox<>();
        desplegable_Tratamientos = new javax.swing.JComboBox<>();
        desplegable_Centro = new javax.swing.JComboBox<>();
        title_TratamientoPaciente = new javax.swing.JLabel();

        jButton2.setBackground(new java.awt.Color(235, 235, 235));
        jButton2.setFont(new java.awt.Font("David Libre", 0, 11)); // NOI18N
        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(159, 211, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_Siguiente_RegistroPT.setBackground(new java.awt.Color(235, 235, 235));
        boton_Siguiente_RegistroPT.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Siguiente_RegistroPT.setText("Aceptar");
        boton_Siguiente_RegistroPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Siguiente_RegistroPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Siguiente_RegistroPTActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Siguiente_RegistroPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 80, 27));

        boton_Volver_RegistroPT.setBackground(new java.awt.Color(235, 235, 235));
        boton_Volver_RegistroPT.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton_Volver_RegistroPT.setText("Volver");
        boton_Volver_RegistroPT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boton_Volver_RegistroPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_Volver_RegistroPTActionPerformed(evt);
            }
        });
        jPanel1.add(boton_Volver_RegistroPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 80, 27));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flo 1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 154, 110));

        label_Fecha_Trata.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Fecha_Trata.setText("Fecha del tratamiento: ");
        jPanel2.add(label_Fecha_Trata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        label_Numero_TratamientoPaciente.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Numero_TratamientoPaciente.setText("Número de documento:");
        jPanel2.add(label_Numero_TratamientoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        label_Tratamiento.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Tratamiento.setText("Tratamiento:");
        jPanel2.add(label_Tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label_Centro.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_Centro.setText("Centro de salud (si aplica):");
        jPanel2.add(label_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        label_EstadoReposo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        label_EstadoReposo.setText("Reposo en: ");
        jPanel2.add(label_EstadoReposo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        desplegable_calendarTrata.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jPanel2.add(desplegable_calendarTrata, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 20));

        desplegable_EstadoReposo.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_EstadoReposo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Hospital" }));
        desplegable_EstadoReposo.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_EstadoReposo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, -1));

        desplegable_NacionalidadTratamientoPaciente.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_NacionalidadTratamientoPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E" }));
        desplegable_NacionalidadTratamientoPaciente.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_NacionalidadTratamientoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 160, -1));

        desplegable_Tratamientos.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Tratamientos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Tratamientos.setPreferredSize(new java.awt.Dimension(56, 24));
        desplegable_Tratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desplegable_TratamientosActionPerformed(evt);
            }
        });
        jPanel2.add(desplegable_Tratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 180, -1));

        desplegable_Centro.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        desplegable_Centro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        desplegable_Centro.setPreferredSize(new java.awt.Dimension(56, 24));
        jPanel2.add(desplegable_Centro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 180, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 57, 470, 300));

        title_TratamientoPaciente.setFont(new java.awt.Font("Forte", 0, 24)); // NOI18N
        title_TratamientoPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_TratamientoPaciente.setText("Tratamiento aplicado a paciente");
        jPanel1.add(title_TratamientoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 40));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_Volver_RegistroPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Volver_RegistroPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Volver_RegistroPTActionPerformed

    private void boton_Siguiente_RegistroPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_Siguiente_RegistroPTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_Siguiente_RegistroPTActionPerformed

    private void desplegable_TratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desplegable_TratamientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_desplegable_TratamientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarTratamientoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarTratamientoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarTratamientoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarTratamientoPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrarTratamientoPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Siguiente_RegistroPT;
    private javax.swing.JButton boton_Volver_RegistroPT;
    private javax.swing.JComboBox<String> desplegable_Centro;
    private javax.swing.JComboBox<String> desplegable_EstadoReposo;
    private javax.swing.JComboBox<String> desplegable_NacionalidadTratamientoPaciente;
    private javax.swing.JComboBox<String> desplegable_Tratamientos;
    private com.toedter.calendar.JDateChooser desplegable_calendarTrata;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_Centro;
    private javax.swing.JLabel label_EstadoReposo;
    private javax.swing.JLabel label_Fecha_Trata;
    private javax.swing.JLabel label_Numero_TratamientoPaciente;
    private javax.swing.JLabel label_Tratamiento;
    private javax.swing.JLabel title_TratamientoPaciente;
    // End of variables declaration//GEN-END:variables
}
